[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.20"
remappings = ["forge-std/=lib/forge-std/src/"]
optimizer = true
optimizer_runs = 200

[rpc_endpoints]
hyperevm = "${HYPEREVM_RPC_URL}"
mainnet = "${RPC_URL}"

[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}" }

